### ISSUE TITLE
Idea: Add support for Adafruit NeoPixels or other addressable LEDs?

### ISSUE THREAD

**Issue by 3871968** [xythobuz/CaseLights#1]
I had an idea for this to use Adafruit NeoPixels (https://learn.adafruit.com/adafruit-neopixel-uberguide/overview) or other addressable LED strips, which contain individually controllable RGB LEDs. This would allow for more flexibility in the way data is displayed.

**Comment by xythobuz** [comment]
Well that would be a considerable increase in complexity required for everything, the App, the Sketch, the communication protocol between the two.

Good idea, but I think it's larger than the scope of this project :)
